pid_controller:
  ros__parameters:

    detection_timeout: 0.5
    alpha: 0.8
    #x: ku:0.8 Tu:2sec
    #z: ku:0.9 Tu:0.5sec
    Ke.x: 0.7
    Ke.y: 0.7
    Ke.z: 0.5

    Kd.x: 0.08
    Kd.y: 0.08
    Kd.z: 0.34

    Ki.x: 0.0
    Ki.y: 0.0
    Ki.z: 0.0


    limit.x: 3.0
    limit.y: 3.0
    limit.z: 0.8